/**
 * Copyright (C) 2024-2026 jango_blockchained
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Bun-built Node + browser ESM bundles + a flat public .d.ts.
 * Source remains the Bun entry (`src/index.ts`). Dist is gitignored and
 * produced on `bun run build` / `npm pack` (prepack).
 */
import { mkdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const entry = join(root, "src/index.ts");

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

function bundle(outfile: string, target: "node" | "browser", minify: boolean): void {
  const args = [
    "build",
    entry,
    "--target",
    target,
    "--format",
    "esm",
    "--outfile",
    outfile,
    "--packages",
    "bundle",
  ];
  if (minify) args.push("--minify");
  const r = Bun.spawnSync(["bun", ...args], { cwd: root, stdout: "inherit", stderr: "inherit" });
  if (r.exitCode !== 0) throw new Error(`bun build failed (${target})`);
  const kb = (statSync(outfile).size / 1024).toFixed(0);
  console.log(`${target.padEnd(8)} ${outfile.replace(root + "/", "")}  ${kb} kB`);
}

const PUBLIC_DTS = `/**
 * Public API of @hoox/pynets (generated by scripts/build.ts).
 * Matches src/index.ts. Interpret only — no compile backend.
 */
export type ParseMode = "exec" | "eval";

export type ASTKind = string;
export interface AST {
  readonly kind: ASTKind;
  lineno?: number;
  col_offset?: number;
  end_lineno?: number | null;
  end_col_offset?: number | null;
}
export interface Script extends AST {
  kind: "Script";
  body: unknown[];
  annotations: string[];
}
export interface Expression extends AST {
  kind: "Expression";
  body: unknown;
}

export class PinescriptSyntaxError extends Error {
  name: "PinescriptSyntaxError";
  lineno: number | null;
  col_offset: number | null;
  constructor(message: string, lineno?: number | null, col_offset?: number | null);
}

export function parse(source: string, filename?: string, mode?: ParseMode): AST;
export function unparse(node: AST): string;
export function dump(node: AST, options?: { annotate_fields?: boolean; include_attributes?: boolean }): string;
export function tokenize(source: string): unknown[];

export type Cell = number | null;
export const NA: null;

export class PineSeries {
  push(value: Cell): void;
  setCurrent(value: Cell): void;
  readonly current: Cell;
  get(offset: number): Cell;
  readonly length: number;
}

export interface OHLCVBar {
  open?: number;
  high?: number;
  low?: number;
  close?: number;
  volume?: number;
  time?: number;
}
export type InputOverrides = Record<string, number | string | boolean>;
export interface BrokerSettings {
  commission?: number;
  slippage?: number;
  pyramiding?: number;
}
export interface RuntimeOptions {
  inputs?: InputOverrides;
  broker?: BrokerSettings;
  timeframe?: string | null;
  libraries?: LibraryRegistry;
}
export interface RuntimeFill {
  type: "fill";
  bar: number;
  id: string;
  side: "buy" | "sell";
  qty: number;
  price: number;
}
export interface StrategyEvent {
  type: string;
  id: string;
  direction?: string;
  qty?: number | null;
  bar: number;
}
export interface StrategySummary {
  netprofit: number;
  netprofitPercent: number;
  openprofit: number;
  equity: number;
  wintrades: number;
  losstrades: number;
  eventrades: number;
  closedtrades: number;
  opentrades: number;
  grossprofit: number;
  grossloss: number;
  avgTrade: number;
  avgWinningTrade: number;
  avgLosingTrade: number;
  percentProfitable: number;
  profitFactor: number;
  maxDrawdown: number;
  maxDrawdownPercent: number;
  maxRunup: number;
  maxRunupPercent: number;
  initialCapital: number;
}
export interface DrawingEvent {
  kind: string;
  bar: number;
  text?: string;
  extra?: Record<string, unknown>;
  deleted?: boolean;
}
export interface LogRecord {
  level: LogLevel;
  bar: number;
  message: string;
}
export type LogLevel = "INFO" | "WARNING" | "ERROR";
export interface RuntimeResult {
  series: Record<string, Array<number | null>>;
  plots: Array<number | null>;
  plot_meta: Array<{ title: string }>;
  count: number;
  script_name: string | null;
  script_type: string;
  mode: "interpret";
  events?: StrategyEvent[];
  fills?: RuntimeFill[];
  drawings?: DrawingEvent[];
  logs?: LogRecord[];
  plot_data?: Record<string, { data: Array<{ value: number | null; time?: number }> }>;
  strategy?: StrategySummary;
  error?: string;
  error_kind?: string;
}
export type StreamEvent = "bar" | "error" | "end";

export class Runtime {
  readonly symbol: string;
  readonly inputs: InputOverrides;
  readonly broker: BrokerSettings;
  readonly timeframe: string | null;
  readonly libraries: LibraryRegistry;
  constructor(symbol?: string, options?: RuntimeOptions);
  registerLibrarySource(namespace: string, name: string, version: number, source: string): void;
  run(source: string, ohlcv: OHLCVBar[], extra?: RuntimeOptions | InputOverrides): RuntimeResult;
  stream(source: string): RuntimeStream;
  runProvider(
    source: string,
    provider: BarProvider,
    extra?: RuntimeOptions & { limit?: number },
  ): Promise<RuntimeResult>;
}
export class RuntimeStream {
  on(event: "bar", handler: (out: RuntimeResult) => void): this;
  on(event: "error", handler: (err: Error) => void): this;
  on(event: "end", handler: (out: RuntimeResult) => void): this;
  push(bar: OHLCVBar): this;
  end(): RuntimeResult;
}
export function interpret(source: string, ohlcv: OHLCVBar[]): { plots: Array<number | null> };
export function interpretTree(
  tree: AST,
  ohlcv: OHLCVBar[],
  host?: {
    symbol?: string;
    inputs?: InputOverrides;
    broker?: BrokerSettings;
    timeframe?: string | null;
    libraries?: LibraryRegistry;
  },
): RuntimeResult;

export class TaEngine {
  [key: string]: unknown;
}

export class PineArray {
  constructor(size?: number, initial?: Cell);
  size(): number;
  get(index: number): Cell;
  set(index: number, value: Cell): void;
  push(value: Cell): void;
  pop(): Cell;
  static from(...values: Cell[]): PineArray;
}
export class PineMap {
  size(): number;
  put(key: unknown, value: Cell): void;
  get(key: unknown): Cell;
  contains(key: unknown): boolean;
  remove(key: unknown): Cell;
  clear(): void;
  putAll(other: PineMap): void;
  keys(): Array<string | number>;
  values(): Cell[];
  copy(): PineMap;
}
export class PineMatrix {
  constructor(rows?: number, cols?: number, initial?: Cell);
  rows(): number;
  columns(): number;
  get(row: number, col: number): Cell;
  set(row: number, col: number, value: Cell): void;
}

export class DrawingBook {
  readonly items: DrawingEvent[];
}

export interface ProviderBar {
  open?: number;
  high?: number;
  low?: number;
  close?: number;
  volume?: number;
  time?: number;
}
export interface BarProvider {
  fetch(opts: { symbol: string; timeframe?: string | null; limit?: number }): Promise<ProviderBar[]>;
}
export class ProviderError extends Error {
  readonly status?: number;
  constructor(message: string, status?: number);
}
export interface JsonBarProviderOptions {
  url?: (opts: { symbol: string; timeframe?: string | null; limit?: number }) => string;
  fetch?: typeof fetch;
  map?: (json: unknown) => ProviderBar[];
  headers?: Record<string, string>;
  fetchBars?: (opts: {
    symbol: string;
    timeframe?: string | null;
    limit?: number;
  }) => Promise<unknown> | unknown;
}
export class MemoryProvider implements BarProvider {
  constructor(bars: ProviderBar[]);
  fetch(opts: { limit?: number }): Promise<ProviderBar[]>;
}
export class StaticMapProvider implements BarProvider {
  constructor(feeds: Record<string, ProviderBar[]>);
  fetch(opts: { symbol: string; timeframe?: string | null; limit?: number }): Promise<ProviderBar[]>;
}
export class JsonBarProvider implements BarProvider {
  constructor(opts: JsonBarProviderOptions);
  fetch(opts: { symbol: string; timeframe?: string | null; limit?: number }): Promise<ProviderBar[]>;
}
export function mapJsonBars(json: unknown): ProviderBar[];

export class LibraryModule {
  title: string;
  namespace: string | null;
  version: number | null;
  get(name: string): unknown;
  has(name: string): boolean;
}
export class LibraryRegistry {
  register(module: LibraryModule): void;
  registerSource(namespace: string, name: string, version: number, source: string): void;
  getSource(namespace: string, name: string, version: number): string | null;
  lookup(query: { namespace?: string | null; name: string; version?: number | null }): LibraryModule | null;
  clear(): void;
}
export function createStubModule(title: string): LibraryModule;
export function applyStubExport(name: string, args?: unknown[], kwargs?: Record<string, unknown>): unknown;
export const STUB_KNOWN_EXPORTS: Record<string, (...args: unknown[]) => unknown>;

export interface UtcParts {
  year: number;
  month: number;
  dayofmonth: number;
  hour: number;
  minute: number;
  second: number;
  dayofweek: number;
}
export function utcPartsFromMs(ms: number): UtcParts;
export function timestampFromComponents(
  year: number | null | undefined,
  month: number | null | undefined,
  day: number | null | undefined,
  hour?: number | null,
  minute?: number | null,
  second?: number | null,
  tzOffsetMinutes?: number | null,
): number | null;
export function parseTimestampString(text: string): number | null;
export function timestamp(...args: unknown[]): number | null;
export function weekOfYear(ms: number): number | null;
export function timeTradingDay(ms: number): number | null;

export class LogBook {
  readonly records: LogRecord[];
  info(bar: number, message: string): void;
  warning(bar: number, message: string): void;
  error(bar: number, message: string): void;
  clear(): void;
  snapshot(): LogRecord[];
}
export class RuntimeError extends Error {
  name: "RuntimeError";
}
export function runtimeError(message: string): never;

export class TickerId {
  symbol: string;
  session?: string;
  adjust?: string;
  heikinashi: boolean;
  renko: boolean;
  kagi: boolean;
  linebreak: boolean;
  pointfigure: boolean;
  toString(): string;
}
export function tickerNew(symbol: string, session?: string, adjust?: string): TickerId;
export function tickerHeikinashi(symbol: string): TickerId;
export function tickerStandard(symbol: string): TickerId;
export function tickerRenko(symbol: string): TickerId;
export function tickerKagi(symbol: string): TickerId;
export function tickerLinebreak(symbol: string): TickerId;
export function tickerPointfigure(symbol: string): TickerId;
export function tickerModify(
  ticker: TickerId | string,
  opts?: { symbol?: string; session?: string; adjust?: string; adjustment?: string },
): TickerId;

export class UdtType {
  readonly name: string;
  newInstance(overrides?: Record<string, unknown>): UdtInstance;
}
export class UdtInstance {
  readonly typeName: string;
  get(field: string): unknown;
  set(field: string, value: unknown): void;
}
export class EnumType {
  readonly name: string;
  readonly members: Map<string, EnumMember>;
}
export class EnumMember {
  readonly enumName: string;
  readonly name: string;
  readonly value?: unknown;
  equals(other: unknown): boolean;
  toString(): string;
}
`;

bundle(join(dist, "index.js"), "node", false);
bundle(join(dist, "browser.js"), "browser", true);
writeFileSync(join(dist, "index.d.ts"), PUBLIC_DTS);
console.log("types    dist/index.d.ts");

